name: build-test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-node@v2.4.1
      with:
         node-version: '14.x'
    - name: install puppeteer libraries
      run: |
       sudo apt-get update && apt-get install -y libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb libgbm-dev
    - name: use yarn
      run: |
       yarn install
       yarn test
